#!/usr/bin/python3
"""
Generates a .tgz archive from the contents of the web_static folder.
"""


from fabric.api import local, run, put, env
from datetime import datetime
import os


env.hosts = ['52.91.168.145', '54.236.17.91']
env.user = "ubuntu"


def do_pack():
    """ Generates .tgz archive from contents of web_static folder

        Returns:
            str: The path to generated archive on success, else None
    """

    local("mkdir -p versions")

    time_str = datetime.utcnow().strftime('%Y%m%d%H%M%S')

    arch_name = "versions/web_static_{}.tgz".format(time_str)

    result = local("tar -cvzf {} web_static".format(arch_name))

    if result.succeeded:
        return arch_name
    else:
        return None


def do_deploy(archive_path):
    """ Distributes an archive to your web servers """

    if os.path.exists(archive_path):
        put(archive_path, '/tmp/')

        arch_name = archive_name = archive_path.split('/')[-1].replace('.tgz', '')
        path = '/data/web_static/releases/' + arch_name
        arch_path = '/tmp/' + arch_name + '.tgz'

        run("mkdir -p {}".format(path))
        run("tar -xzf {} -C {}".format(arch_path, path))
        run("rm {}".format(arch_path))
        run('mv /data/web_static/releases/{}/web_static/* \
            /data/web_static/releases/{}/'.format(filename, filename))
        run('rm -rf /data/web_static/releases/{}/web_static'
            .format(filename))
        run("rm -rf /data/web_static/current")
        run("ln -s {} /data/web_static/current".format(path))

        return True
    else:
        return False
